### ISSUE TITLE
About the classification under node attack experiment 

### ISSUE THREAD

**Issue by zhangxiaozao** [huawei-noah/BGCN#1]
Hi~ Thanks for your code about the bayesian gcn, is there the code for classification under node attack experiment?
Looking forward for your reply!

**Comment by maggie0106** [comment]
Hi Xiaozao,

We are following the same setting as the Nettack paper and use their code for the experiment setting. Please refer to their repo here: https://github.com/danielzuegner/nettack 

best,
Yingxue
